### ISSUE TITLE
Passing model to the fields

### ISSUE THREAD

**Issue by HeadStudios** [pavloniym/nova-action-buttons#4]
What is your recommendation for being able to access the resource calling the action button from within the fields() function? 

Attempts for reference below:
https://ibb.co/wNBYdLV 

Video for reference:
https://share.getcloudapp.com/d5ugW6JY

**Comment by pavloniym** [comment]
Oh, great dialog with ChatGTP))
Try this:

```php
// TorrentResource.php
ActionButton::make('')
  ->icon('<svg></svg>')
  ->action(new UpdateTorrentAction($this->resource), $this->resource->id)

```


```php

// UpdateTorrentAction


/**
 * @param Torrent $torrent
 */
public function __construct(Torrent $torrent)
{
    $this->torrent = $torrent;
}

/**
 * Get the fields available on the action.
 *
 * @param NovaRequest $request
 * @return array|null
 */
public function fields(NovaRequest $request): ?array
{
    // $request is empty if action is called from index row (or inline)
    // so use instance injected to action constructor
    $torrent = (fn(): ?Torrent => $request?->selectedResources()?->first())();
    $torrent = $torrent ?? $this->torrent;

    if ($torrent) {
         ...
    }

    return null;
}

```

**Comment by pavloniym** [comment]
And register your action in resource class this way:

```php
// TorrentResource.php

/**
 * Get the actions available on the entity.
 *
 * @param Request $request
 * @return array
 */
public function actions(Request $request)
{
    return [
        UpdateTorrentAction::make(),
    ];
}
```

**Comment by HeadStudios** [comment]
Hi,

Thank you for your quick response.

Please find below my modified files as per your instructions:
Touchpoint.php - https://gist.github.com/HeadStudios/9a6befc480556aeb295edc983c4bed4f (resource model)
OppHit.php - https://gist.github.com/HeadStudios/7c1eada4472d65d32a4eaabe0203118d (Action)

Unfortunately I am unable to get the argument passed between the ActionButton and the to the Action's constructor method, I get the error below:

Error: 
[2023-03-17 10:12:36] local.ERROR: Too few arguments to function App\Nova\Actions\OppHit::__construct(), 0 passed in /var/www/vendor/laravel/nova/src/Makeable.php on line 14 and exactly 1 expected {"userId":1,"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function App\\Nova\\Actions\\OppHit::__construct(), 0 passed in /var/www/vendor/laravel/nova/src/Makeable.php on line 14 and exactly 1 expected at /var/www/app/Nova/Actions/OppHit.php:39)
[stacktrace]

Video for reference:
https://p147.p4.n0.cdn.getcloudapp.com/items/kpuA54PP/7cb3b7a0-5b8d-4f5f-9110-1c41ed4e4745.mp4?v=9fc795e0fe507589e34595f09ccd0f96

Anything I'm missing please let me know.

Note: in the video I didn't add the UpdateTorrentAction::make() updated syntax as per your suggestion however I have done this after and it still hasn't worked for me.

**Comment by pavloniym** [comment]
@HeadStudios 
As I understand your situation:
Error on frontend is caused by `actions` method of your resource class (`Touchpoint.php`)

 Use `OppHit::make()` in `actions` array, because static `make` method uses Laravel  resolve for dependency injection in your `OppHit.php` constructor.

Because your `OppHit` action is constructed on `Touchpoint` resource initialization — you can not pass any parameter to constructor on this stage. Use default value (`__construct(int $number = 0)` or type hint for Laravel DI (`__construct(Touchpoint $touch)`)

So, `69` line in your `OppHit` action will get `Touchpoint` instance on default Nova action use (by selecting on index row by checkbox or by executing action from dropdown on detail page ) and `70` line will be use on `ActionButton` press (when your `OppHit` action will be initialized with provided instance in constructor)

I hope this will help you!

**Comment by HeadStudios** [comment]
Thank you, this has fixed my issue! You're a lifesaver. Marking this closed. For anyone interested full code is below (for creating SMS send action button that populates name in textarea)

https://gist.github.com/HeadStudios/f4235359f00315e548ab7034bef8bec5 
https://gist.github.com/HeadStudios/c5b93a1e32ed1b7b0c05e146ef6958c3
